openapi: 3.0.0
info:
  title: YeGoBox Api
  description: A Simple minimalistic api for yegobox
  contact:
    email: info@yegobox.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  - url: 'https://yegobox.rw'
    description: API SERVER
  - url: 'https://yegobox.rw/api'
    description: Api
